/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Serial */

#ifndef _Included_Serial
#define _Included_Serial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Serial
 * Method:    openPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Serial_openPort
  (JNIEnv *, jobject);

/*
 * Class:     Serial
 * Method:    write
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Serial_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     Serial
 * Method:    read
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_Serial_read
  (JNIEnv *, jobject);

/*
 * Class:     Serial
 * Method:    closePort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Serial_closePort
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
